# Generated by Django 4.0 on 2022-03-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artgallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='ch',
            field=models.CharField(choices=[('1', 'Colour Portraits'), ('2', 'Cross Hatching'), ('3', 'Graphite Portraits'), ('4', 'Doodles')], default='1', max_length=50),
        ),
    ]
